# Generated by Django 5.1.2 on 2025-01-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
