# Generated by Django 5.1.2 on 2025-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_alter_chatroom_name_alter_chatroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
